name: mongodb

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: run tests
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: update /etc/hosts
        run: |
          sudo echo "172.17.0.1 host.docker.internal" | sudo tee -a /etc/hosts
          cat /etc/hosts
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version-file: "./MongoDB/.nvmrc"
      - name: start mongodb
        run: |
          cd MongoDB
          docker network create mongodb
          docker run -d -p 27017:27017 --name mongodb --network mongodb --rm mongo:5.0.26
      - name: info
        run: |
          node --version
          npm --version
          docker ps
      - name: wait for MongoDB
        run: |
          cd MongoDB
          ./wait/wait.sh
      - name: run the tests
        run: |
          cd MongoDB
          npm install
          npm test
